config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :accounts do
    member do
      get 'connect'      
    end
  end
  
  resources :products do
    collection do
      get 'averedge'
      get 'sum'
      get 'extremums'
      get 'onlyTV'
      get 'cheap'
    end
    member do
      get 'add_to_cart'      
    end
  end  

  root 'welcome#welcome'

  get 'cart' => 'cart#get_owner'
  get 'cart/products' => 'cart#show_products'
  get 'cart/products/order' => 'cart#make_order'

end

app/models/product.rb
class Product < ActiveRecord::Base
	#has_one :gallery
	has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	belongs_to :cart
	validates :name, presence: true
	validates :price, numericality: {greater_than: 0}

	#is_impressionable :counter_cache => true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_locale, :set_product, only: [:show, :edit, :update, :destroy, :add_to_cart]
  before_filter :authenticate_user!

  #@widget.impressionist_count(:filter=>:all)

  def sum
    @price_sum = Product.sum(:price)
  end

  def averedge
    @averedge_price = Product.average(:price)
  end

  def extremums
    @temp = Product.order(price: :desc)
    @max = @temp[0]
    @min = @temp[-1]
  end

  def onlyTV 
    @TVinclude = Product.where(name:'TV')
  end

  def cheap
    @cheap = Product.where('price<?',100)
  end

  # GET /products
  # GET /products.json
  def index
    #@widget = Widget.find(impressionist(@widget, "message...")) # 2nd argument is optional
    #@widget.impressionist_count(:filter=>:all)
    text = params["text"].presence
    #binding.pry
    @products = Product.all    
    @products = @products.where(name: text) if text
    @products = @products.order(:price)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    #binding.pry
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "#{@product.name} was successfully created."}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
      if @product.update(product_params)
          redirect_to @product, notice: "#{@product.name} was successfully updated."
        else
          render :edit
        end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "#{@product.name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end 

  def add_to_cart
    account = current_user.account
    if account && account.cart
      cart = account.cart
      @product.cart = cart
      @product.save
      redirect_to products_path, notice: "#{@product.name} has been added to the cart."
    else
      redirect_to cart_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.where(id: params[:id]).first
      render_404 unless @product
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end

    def set_locale
      I18n.locale = :uk
      #binding.pry
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
  <%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/add_to_cart.html.erb
Це ніхто не має БАЧИТИ!!!!!!!!!	


Product
<%= @product.name %>
has been added to your cart, mister
<%= @account.name%>
<%=link_to "До продуктів", products_path%>

app/views/products/averedge.html.erb
<p> averedge prise:<p>
<%= @averedge_price%>

app/views/products/cheap.html.erb
<p> cheap products  <p>
<% @cheap.each do |t| %>
<p>	<%= p("#{t.name}     #{t.price}") %> <p>
<%	end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/extremums.html.erb
<p> max sum:<p>
<%= p("#{@max.name}     #{@max.price}") %>
<p> min sum:<p>
<%= p("#{@min.name}     #{@min.price}") %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <% @products.each do |p|%>
    <div class="col-sm-2 col-md-4">
      <div class="thumbnail">
        <%=image_tag p.image.url, class: "my-image"%> 
        <!--<img data-src="holder.js/300x300" alt="No picture available">-->

        <div class="caption">
          <h4><%=p.name%></h4>
          <p class="well well-sm">Опис:<%=p.description%></p>
          <p>Ціна:<%=p.price%></p>
          <p >
            <%=link_to 'Переглянути', p, class:"btn btn-default" %>
            <% if current_user.account && current_user.account.cart &&current_user.account.cart.products.include?(p) %>
              <div class="btn btn-default" disabled="disabled">З тебе хватить!</div>
            <%else%>
              <%=link_to 'Додати у корзину', add_to_cart_product_path(p), class: "btn btn-default"%>
            <%end%>

          </p>
        </div>
      </div>
    </div>  
  <%end%>
</div>

<h2>List of Products</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Show</th>
      <th>Add to cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @products.present? %>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= link_to 'Show', product %></td>
          <% if current_user.account && current_user.account.cart.blank? %>
            <td><%= link_to 'Додати цей товар у корзину', cart_path %></td>
          <% elsif current_user.account && current_user.account.cart.products.include?(product) %>
            <td> з тебе хватить!</td>
          <% else %>
            <td><%= link_to 'Додати цей товар у корзину', add_to_cart_product_path(product) %></td>
          <% end %>
          
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center"> No results </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/onlyTV.html.erb
<p> our TV:<p>
<% @TVinclude.each do |t| -%>
<%= p("#{t.name}     #{t.price}" )%>
<% end%>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Images:</strong>
<%= image_tag @product.image.url, size: '300x300' %>
</p>

<%= link_to 'Back', products_path %>
<%= link_to 'Add to the cart', add_to_cart_product_path(@product) %>

app/views/products/sum.html.erb
<p> prices sum:<p>
<%= @price_sum %>