config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :accounts do
    member do
      get 'connect'      
    end
  end
  
  resources :products do
    collection do
      get 'averedge'
      get 'sum'
      get 'extremums'
      get 'onlyTV'
      get 'cheap'
    end
    member do
      get 'add_to_cart'      
    end
  end  

  root 'welcome#welcome'

  get 'cart' => 'cart#get_owner'
  get 'cart/products' => 'cart#show_products'
  get 'cart/products/order' => 'cart#make_order'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    #circle {background-color: red;
      position: absolute;
      height: 100px;
      width: 100px;
      left: 200px;
      top: 0px;
      border-radius: 50%;
    }
  </style>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ModelsHW</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>



<body>
<div class="container-fluid">


  <nav class="navbar navbar-inverse navbar fixed top" role="navigation">
    <div class="container-fluid">
      
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>              
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%=link_to "LotR shop", root_path , class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li > <%= link_to 'Products', products_path %> </li>
          <li > <%= link_to 'Cart', cart_path %> </li>
          <li > <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %> </li>
        </ul>

        <%= form_tag products_path, method: "get", class: "navbar-form navbar-left" do %>
        	<div class="form-group">
        		<%= text_field_tag :text, nil, class:"form-control", placeholder:"Введіть назву товару" %>
        	</div>
        	<%= submit_tag "Пошук", class:"btn btn-default" %>
        <% end %>

        <div class="pull-right">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to 'Вийти', destroy_user_session_path, :method => :delete %></li>
              <li class="btn btn-default">
                <% if current_user.account %>
                  <%= link_to "Ваш акаунт:" + current_user.account.name , edit_account_path(current_user.account) %>
                <% else %>
                  <%= link_to 'виберіть акаунт', accounts_path %>
                <% end %>
              </li>

              <li class="btn btn-default">
                <% if current_user.account %>
                  <%= link_to "Ваша пошта:"+current_user.email, accounts_path %>
                <%end%>                 
              </li>   
            <% else %>
              <li class="btn btn-xs btn-default"> <%= link_to 'Зайти', new_user_session_path %> 
              </li>
            <% end %>
          </ul>
        </div>
      </div><!-- /.navbar-collapse -->

    </div><!-- /.container-fluid -->
  </nav>


  <%= yield %>

</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>