config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :accounts do
    member do
      get 'connect'      
    end
  end
  
  resources :products do
    collection do
      get 'averedge'
      get 'sum'
      get 'extremums'
      get 'onlyTV'
      get 'cheap'
    end
    member do
      get 'add_to_cart'      
    end
  end  

  root 'welcome#welcome'

  get 'cart' => 'cart#get_owner'
  get 'cart/products' => 'cart#show_products'
  get 'cart/products/order' => 'cart#make_order'

end

app/models/account.rb
#class GoodNameValidator < ActiveModel::Validator
  def validate(record)
    digits = ['0','1','2','3','4','5','6','7','8','9']
    undigit_presenese = false
    record.name.each_char do |c|
    	undigit_presenese=true if !digits.include?(c)    	
  	end
    unless undigit_presenese
      record.errors[:name] << "Name can not consist from digits only"
    end
  end
#end

class Account < ActiveRecord::Base
	has_one :cart
  belongs_to :user

  validate :not_digits_only
  def not_digits_only
    digits = ['0','1','2','3','4','5','6','7','8','9']
    undigit_presenese = false
    name.each_char do |c|
      undigit_presenese=true if !digits.include?(c)     
    end
    unless undigit_presenese
      errors.add(:name, "Name can not consist digits only")
    end
  end

  #validates_with GoodNameValidator
  validates :name, presence: true, length: {in: 8..20}
  validates :age, presence: true, inclusion: {in: 18..100}
end 

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :connect]
  before_filter :authenticate_user!
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.order(:age)
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    #binding.pry
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def connect
    #@account.user = current_user 
    current_user.account = @account
    #@account.user_id = @user.id
    @account.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.where(id: params[:id]).first
      render_404 unless @account
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :age)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/connect.html.erb
You connect current user with this account

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @account.age %>
</p>

<p>
  <strong>User:</strong>
  <%= @account.user_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts, choose yours</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.age %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Choose_account', "accounts/#{account.id}/connect"
        #connect_account_path(account) 
        %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @account.age %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>